### ISSUE TITLE
Max recursion limit reached

### ISSUE THREAD

**Issue by rishabh004-ai** [vishalnagda1/text-to-speech#1]
The error is always the maximum recursion limit reached for any language or accent.

**Comment by vishalnagda1** [comment]
@rishabh004-ai I need more information about the issue.
Please provide the full detailed error.
Along with your Python version, OS (type and version) detail.

**Comment by rishabh004-ai** [comment]
`Traceback (most recent call last):
  File "main.py", line 96, in <module>
    update_language(reader, language, accent, gender)
  File "main.py", line 68, in update_language
    filtered_voice_list = filter_voice(reader.getProperty(
  File "main.py", line 54, in filter_voice
    return filter_voice(voices, gender, language, accent, False)
  File "main.py", line 54, in filter_voice
    return filter_voice(voices, gender, language, accent, False)
  File "main.py", line 54, in filter_voice
    return filter_voice(voices, gender, language, accent, False)
  [Previous line repeated 992 more times]
  File "main.py", line 50, in filter_voice
    filter_list = [voice for voice in voices if filter_rule(
  File "main.py", line 50, in <listcomp>
    filter_list = [voice for voice in voices if filter_rule(
  File "main.py", line 45, in filter_rule
    return voice.languages[0] == (language + '_' + accent)
RecursionError: maximum recursion depth exceeded in comparison
`
Python version 3.8.5
Os version Ubuntu 18.04.3
Running the code on Nvidia DGX server.
But the same error happens on google colab .

**Comment by vishalnagda1** [comment]
@rishabh004-ai Thank you for sharing the full error trace  and environment specific details. I need further more input like what test case you're running to generate the error. I tried to reproduce the same error on my local system as well as on my AWS Ubuntu based servers. But I'm not able to reproduce the same trace.

**Comment by rishabh004-ai** [comment]
Hey Vishal, I have just run the `python main.py -t "This is input from the command line"`. And the error comes as the recursion depth limit reached. I have tested this on multiple systems but the error remains the same. If you want I can run this code on colab and share it with you.

**Comment by vishalnagda1** [comment]
@rishabh004-ai I have updated the code and the readme file.
If you're facing any issues related to the application; refer the [Troubleshooting](https://github.com/vishalnagda1/text-to-speech#troubleshooting) section in README file.
